# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6286d7f1f2f14291dd13ec44bcdc84f46f10071ca55543adc16a1dcf2f2fcf6bf219e2e9c50c71a3d0521c79d06194038eb44297809d746d655e82e260d81ec8

test:
  secret_key_base: db6a51b452b5a3e3ec6ae76d0f1451f39204a3c58d4c04c42fcc1b8a6dfc28490e7327d810fad43837c59c913a026815a8fc3626795c2470c9e1eecd078b700d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
